### ISSUE TITLE
IndexError: List index out of range

### ISSUE THREAD

**Issue by Anishbekal** [Sterncat/opticspy#18]
Hi,
I was trying to install opticspy. I have Anaconda system on windows with Spyder 3. 1.4 and Python 3.6 installed. 
I got the following error: Please suggest a remedy

!pip install opticspy
Collecting opticspy
  Downloading opticspy-0.2.1.tar.gz (1.3MB)
Requirement already satisfied: numpy>=1.9.3 in c:\programdata\anaconda3\lib\site-packages (from opticspy)
Requirement already satisfied: matplotlib>=1.4.3 in c:\programdata\anaconda3\lib\site-packages (from opticspy)
Collecting unwrap (from opticspy)
  Downloading unwrap-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 474, in __init__
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\abekal\AppData\Local\Temp\pip-build-ywxkot1x\unwrap\setup.py", line 14, in <module>
        import unwrap.unwrap2D as unwrap2D
      File "C:\Users\abekal\AppData\Local\Temp\pip-build-ywxkot1x\unwrap\unwrap\__init__.py", line 3, in <module>
        from unwrap.unwrap import unwrap
      File "C:\Users\abekal\AppData\Local\Temp\pip-build-ywxkot1x\unwrap\unwrap\unwrap.py", line 4, in <module>
        from unwrap.unwrap2D import unwrap2D
      File "C:\Users\abekal\AppData\Local\Temp\pip-build-ywxkot1x\unwrap\unwrap\unwrap2D.py", line 20, in <module>
        include_dirs=[_current_directory])
      File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\api.py", line 438, in verify
        lib = self.verifier.load_library()
      File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\verifier.py", line 114, in load_library
        self._compile_module()
      File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\verifier.py", line 211, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 20, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 49, in _build
        dist.run_command('build_ext')
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\build_ext.py", line 77, in run
      File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 193, in build_extensions
        self.build_extension(ext)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\build_ext.py", line 198, in build_extension
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 170, in msvc14_get_vc_env
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 767, in __init__
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 477, in __init__
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\abekal\AppData\Local\Temp\pip-build-ywxkot1x\unwrap\

Thank you
Anish bekal

**Comment by Anishbekal** [comment]
Not a problem with opticspy. Xing suggested me to install "Microsoft Visual C++ Build tools". Problem solved
