### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by dibyendumajumdar** [Sterncat/opticspy#33]
Hi
I am getting following error. I am  on Redhat 7.7 and using Python 3.6.

```
Python 3.6.3 (default, Apr 10 2019, 14:37:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from opticspy.ray_tracing import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dylan/pydev/lib64/python3.6/site-packages/opticspy/__init__.py", line 12, in <module>
    import aperture, interferometer_seidel,interferometer_zenike
ModuleNotFoundError: No module named 'aperture'
```

Any idea what might be wrong?

Thank you

**Comment by dibyendumajumdar** [comment]
Looks like this is duplicate of issue #20 
I managed to import successfully after installing `pyyaml` and installing opticspy as suggested in issue #20 
```
pip install git+git://github.com/Sterncat/opticspy.git@master
```

Now to check if it works
